version: "3"
services:
  node:
    image: "node:21"
    user: "node"
    container_name: node-react
    working_dir: /home/node/app
    volumes:
      - ./app:/home/node/app
    expose:
      - "3000"
    ports:
      - "3000:3000"
    tty: true
